---
type: CheckConfig
api_version: core/v2
metadata:
  name: check-tomcat-port
  namespace: default
spec:
  command: check-ports.rb   -p 8443,8080
  handlers: [email,slack]
  interval: 10
  publish: true
  runtime_assets:
  - network-check
  - sensu-ruby-runtime
  subscriptions:
  - tomcat

