---
type: CheckConfig
api_version: core/v2
metadata:
  name: check-cpu
  namespace: default
spec:
  command: check-cpu.rb -w85 -c90
  handlers: [email,slack]
  interval: 60
  publish: true
  runtime_assets:
  - cpu
  - sensu-ruby-runtime
  subscriptions:
  - system

