---
type: CheckConfig
api_version: core/v2
metadata:
  name: check-mongodb-web01
  namespace: default
spec:
  command: check-mongodb.rb -H 10.0.1.5
  handlers: [email,slack]
  interval: 10
  publish: true
  runtime_assets:
  - mongodb
  - sensu-ruby-runtime
  subscriptions:
  - mongo-web01


