---
type: CheckConfig
api_version: core/v2
metadata:
  name: check-socket
  namespace: default
spec:
  command: check-socat.rb -h address  -p49999
  handlers: [email,slack]
  interval: 10
  publish: true
  runtime_assets:
  - network-check
  - sensu-ruby-runtime
  subscriptions:
  - socket

