---
type: CheckConfig
api_version: core/v2
metadata:
  name: check-snmp
  namespace: default
spec:
  command: check-snmp.rb
  handlers: [email,slack]
  interval: 10
  publish: true
  runtime_assets:
  - snmp
  - sensu-ruby-runtime
  subscriptions:
  - snmp

