---
type: CheckConfig
api_version: core/v2
metadata:
  name: check-mongo-ports
  namespace: default
spec:
  command: check-ports.rb  -h  localhost   -p 27017
  handlers: [email,slack]
  interval: 10
  publish: true
  runtime_assets:
  - network-check
  - sensu-ruby-runtime
  subscriptions:
  - mongo

