---
type: CheckConfig
metadata:
  name: met-netif
  namespace: default
spec:
  command: metrics-netif.rb
  handlers: [influx-db,slack,email]
  interval: 60
  publish: true
  output_metric_format: graphite_plaintext
  output_metric_handlers:
   - influx-db
  runtime_assets:
  - network-check
  - sensu-ruby-runtime
  subscriptions:
  - system

