---
type: CheckConfig
metadata:
  name: met-memory-percentage
  namespace: default
spec:
  command: metrics-memory-percent.rb
  handlers: [influx-db,slack,email]
  interval: 60
  publish: true
  output_metric_format: graphite_plaintext
  output_metric_handlers:
   - influx-db
  runtime_assets:
  - memory-checks
  - sensu-ruby-runtime
  subscriptions:
  - system

